name: Node.js CI

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm coverage      

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
